# Generated by Django 4.0.1 on 2022-01-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='name',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
